    <!-- Modern Animated Footer -->
    <footer class="relative bg-gradient-to-br from-red-600 via-red-700 to-red-800 text-white overflow-hidden mt-16">
        <!-- Animated Wave Background -->
        <div class="absolute inset-0 opacity-20">
            <svg class="absolute bottom-0 w-full h-32 wave-animation" viewBox="0 0 1200 120" preserveAspectRatio="none">
                <path d="M0,60 C300,120 600,0 900,60 C1050,90 1150,30 1200,60 L1200,120 L0,120 Z" fill="currentColor"></path>
            </svg>
            <svg class="absolute bottom-0 w-full h-28 opacity-60 wave-animation" viewBox="0 0 1200 120" preserveAspectRatio="none" style="animation-delay: -2s;">
                <path d="M0,80 C400,20 800,100 1200,40 L1200,120 L0,120 Z" fill="currentColor"></path>
            </svg>
        </div>

        <!-- Floating Particles -->
        <div class="absolute inset-0 overflow-hidden pointer-events-none" id="particles-container">
            <!-- Particles will be generated by JavaScript -->
        </div>

        <div class="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
            <!-- Main Footer Content -->
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8 mb-12">
                <!-- Company Info -->
                <div class="space-y-4">
                    <div class="flex items-center space-x-3 group">
                        <h3 class="text-2xl font-bold text-white">
                            Trembesi Shop
                        </h3>
                    </div>
                    <p class="text-red-100 text-sm leading-relaxed font-light">
                        Your trusted partner for industrial procurement solutions, delivering high-quality materials, equipment, and supplies for construction and industrial needs.
                    </p>
                    <div class="flex space-x-4">
                        <a href="#" class="group p-2 bg-gradient-to-r from-white/10 to-white/5 rounded-lg hover:from-white/20 hover:to-white/15 transition-all duration-300 shadow-glow">
                            <i class="fab fa-facebook-f text-red-200 group-hover:text-white transition-colors"></i>
                        </a>
                        <a href="https://trembesiglobal.com/" class="group p-2 bg-gradient-to-r from-white/10 to-white/5 rounded-lg hover:from-white/20 hover:to-white/15 transition-all duration-300 shadow-glow">
                            <i class="fas fa-globe text-red-200 group-hover:text-white transition-colors"></i>
                        </a>
                        <a href="https://www.linkedin.com/in/trembesi-global-energi-60a815112/" class="group p-2 bg-gradient-to-r from-white/10 to-white/5 rounded-lg hover:from-white/20 hover:to-white/15 transition-all duration-300 shadow-glow">
                            <i class="fab fa-linkedin-in text-red-200 group-hover:text-white transition-colors"></i>
                        </a>
                        <a href="https://www.instagram.com/trembesiglobalenergi/" class="group p-2 bg-gradient-to-r from-white/10 to-white/5 rounded-lg hover:from-white/20 hover:to-white/15 transition-all duration-300 shadow-glow">
                            <i class="fab fa-instagram text-red-200 group-hover:text-white transition-colors"></i>
                        </a>
                    </div>
                </div>

                <!-- Quick Links -->
                <div class="space-y-4">
                    <h4 class="text-lg font-semibold text-white">Quick Links</h4>
                    <div class="grid grid-cols-1 gap-2 text-sm">
                        <a href="/material" class="text-red-100 hover:text-white transition-colors flex items-center space-x-2">
                            <i class="fas fa-cube text-xs"></i>
                            <span>Materials</span>
                        </a>
                        <a href="/equipment" class="text-red-100 hover:text-white transition-colors flex items-center space-x-2">
                            <i class="fas fa-tools text-xs"></i>
                            <span>Equipment</span>
                        </a>
                        <a href="/electrical" class="text-red-100 hover:text-white transition-colors flex items-center space-x-2">
                            <i class="fas fa-bolt text-xs"></i>
                            <span>Electrical Tools</span>
                        </a>
                        <a href="/consumables" class="text-red-100 hover:text-white transition-colors flex items-center space-x-2">
                            <i class="fas fa-shopping-bag text-xs"></i>
                            <span>Consumables</span>
                        </a>
                        <a href="/personal" class="text-red-100 hover:text-white transition-colors flex items-center space-x-2">
                            <i class="fas fa-hard-hat text-xs"></i>
                            <span>PPE</span>
                        </a>
                    </div>
                </div>

                <!-- Services -->
                <div class="space-y-4">
                    <h4 class="text-lg font-semibold text-white">Services</h4>
                    <div class="grid grid-cols-1 gap-2 text-sm">
                        <a href="#" class="text-red-100 hover:text-white transition-colors flex items-center space-x-2">
                            <i class="fas fa-boxes text-xs"></i>
                            <span>Bulk Orders</span>
                        </a>
                        <a href="#" class="text-red-100 hover:text-white transition-colors flex items-center space-x-2">
                            <i class="fas fa-cog text-xs"></i>
                            <span>Custom Solutions</span>
                        </a>
                        <a href="#" class="text-red-100 hover:text-white transition-colors flex items-center space-x-2">
                            <i class="fas fa-headset text-xs"></i>
                            <span>Technical Support</span>
                        </a>
                        <a href="#" class="text-red-100 hover:text-white transition-colors flex items-center space-x-2">
                            <i class="fas fa-truck text-xs"></i>
                            <span>Delivery Services</span>
                        </a>
                        <a href="#" class="text-red-100 hover:text-white transition-colors flex items-center space-x-2">
                            <i class="fas fa-shield-alt text-xs"></i>
                            <span>Warranty</span>
                        </a>
                    </div>
                </div>

                <!-- Contact Info -->
            <div class="space-y-4">
                <h4 class="text-lg font-semibold text-white">Contact Us</h4>
                <div class="space-y-3 text-sm">
                    <div class="flex items-start space-x-3 group">
                        <div class="p-1 bg-gradient-to-r from-white/20 to-white/10 rounded group-hover:from-white/30 group-hover:to-white/20 transition-all duration-300 shadow-glow">
                            <i class="fas fa-map-marker-alt text-white text-xs"></i>
                        </div>
                        <span class="text-red-100">
                            DWB Tower Building, 3rd Floor Zone B 01;<br>
                            Jl. Kebagusan 1 Kav.6 Pasar Minggu - South Jakarta<br>
                            INDONESIA 12520
                        </span>
                    </div>
                    <div class="flex items-start space-x-3 group">
                        <div class="p-1 bg-gradient-to-r from-white/20 to-white/10 rounded group-hover:from-white/30 group-hover:to-white/20 transition-all duration-300 shadow-glow">
                            <i class="fas fa-phone text-white text-xs"></i>
                        </div>
                        <span class="text-red-100">+62 21 29406626</span>
                    </div>
                    <div class="flex items-start space-x-3 group">
                        <div class="p-1 bg-gradient-to-r from-white/20 to-white/10 rounded group-hover:from-white/30 group-hover:to-white/20 transition-all duration-300 shadow-glow">
                            <i class="fas fa-envelope text-white text-xs"></i>
                        </div>
                        <div class="flex flex-col">
                            <a href="mailto:info@trembesiglobal.com" class="text-red-100 hover:underline">info@trembesiglobal.com</a>
                            <a href="https://www.trembesiglobal.com" target="_blank" class="text-red-100 hover:underline">www.trembesiglobal.com</a>
                        </div>
                    </div>
                    <div class="flex items-start space-x-3 group">
                        <div class="p-1 bg-gradient-to-r from-white/20 to-white/10 rounded group-hover:from-white/30 group-hover:to-white/20 transition-all duration-300 shadow-glow">
                            <i class="fas fa-clock text-white text-xs"></i>
                        </div>
                        <span class="text-red-100">Mon - Fri: 8:00 AM - 6:00 PM</span>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <script>
        // JavaScript animations for particles
        document.addEventListener('DOMContentLoaded', function() {
            const particlesContainer = document.getElementById('particles-container');
            
            // Create floating particles
            function createParticle() {
                const particle = document.createElement('div');
                particle.className = 'absolute bg-white rounded-full floating-particle';
                
                // Random size between 4px and 12px
                const size = Math.random() * 8 + 4;
                particle.style.width = size + 'px';
                particle.style.height = size + 'px';
                
                // Random position
                particle.style.top = Math.random() * 100 + '%';
                particle.style.left = Math.random() * 100 + '%';
                
                // Random opacity
                particle.style.opacity = Math.random() * 0.4 + 0.2;
                
                // Random animation delay
                particle.style.animationDelay = Math.random() * 6 + 's';
                particle.style.animationDuration = (Math.random() * 4 + 4) + 's';
                
                particlesContainer.appendChild(particle);
                
                // Remove particle after animation completes multiple cycles
                setTimeout(() => {
                    if (particle.parentNode) {
                        particle.parentNode.removeChild(particle);
                    }
                }, 30000);
            }
            
            // Create initial particles
            for (let i = 0; i < 15; i++) {
                setTimeout(() => createParticle(), i * 500);
            }
            
            // Continuously add new particles
            setInterval(createParticle, 2000);
            
            // Wave animation enhancement
            const waves = document.querySelectorAll('.wave-animation');
            waves.forEach((wave, index) => {
                wave.style.animationDelay = (index * -1) + 's';
                wave.style.animationDuration = (8 + index) + 's';
            });
            
            // Add subtle glow effect to icons on hover
            const icons = document.querySelectorAll('.shadow-glow');
            icons.forEach(icon => {
                icon.addEventListener('mouseenter', function() {
                    this.style.boxShadow = '0 0 30px rgba(255, 255, 255, 0.3)';
                });
                
                icon.addEventListener('mouseleave', function() {
                    this.style.boxShadow = '0 0 20px rgba(255, 255, 255, 0.1)';
                });
            });
            
            // Parallax effect for footer background
            let ticking = false;
            
            function updateParallax() {
                const scrolled = window.pageYOffset;
                const footer = document.querySelector('footer');
                const footerTop = footer.offsetTop;
                const footerHeight = footer.offsetHeight;
                const windowHeight = window.innerHeight;
                
                if (scrolled + windowHeight > footerTop) {
                    const rate = (scrolled + windowHeight - footerTop) / footerHeight;
                    const yPos = -(rate * 50);
                    footer.style.backgroundPosition = `center ${yPos}px`;
                }
                
                ticking = false;
            }
            
            function requestParallaxUpdate() {
                if (!ticking) {
                    requestAnimationFrame(updateParallax);
                    ticking = true;
                }
            }
            
            window.addEventListener('scroll', requestParallaxUpdate);
        });
    </script>
